### ISSUE TITLE
Ошибка при получении информации об обновлении

### ISSUE THREAD

**Issue by bolgov0zero** [lumian/aspia-webui#3]
Установил последнюю доступную версию. Все настроил. Но Host выдает ошибку.
<img width="536" alt="image" src="https://user-images.githubusercontent.com/45520996/215255993-7ceef957-d93a-4200-a880-11587246d488.png">

**Comment by alexey-gamov** [comment]
> Установил последнюю доступную версию. Все настроил. Но Host выдает ошибку.

А у вас какой путь в настройках сервера обновлений указан?

**Comment by bolgov0zero** [comment]
> 

Что значит "какой путь"?

**Comment by alexey-gamov** [comment]
> Что значит "какой путь"?

Какой URL указываете в качестве сервера обновлений в Aspia?
