### ISSUE TITLE
Ошибки PHP при запуске установщика

### ISSUE THREAD

**Issue by Genzo4** [lumian/aspia-webui#4]
Здравствуйте.

Скинул содержимое папки upload на web-сервер. Зашёл с браузера, а там на первом же шаге ошибки PHP. Скрины первых ошибок прилагаю.

OS: Debian 11. Все обновления поставлены.
Web-сервер: Apache
PHP: 7.4
на все файлы и папки полный доступ (777)

![изображение_2023-05-02_160915753](https://user-images.githubusercontent.com/46362473/235591674-c3e726b1-2120-4eb2-b163-dc3646cc20f2.png)
![изображение_2023-05-02_160931919](https://user-images.githubusercontent.com/46362473/235591710-7f3bfbd9-2e9d-4d78-9e43-329700c29391.png)
![изображение_2023-05-02_160942195](https://user-images.githubusercontent.com/46362473/235591735-9f82ad6a-4c4a-4b48-8b2d-ccced8665471.png)

**Comment by lumian** [comment]
Настройка "short_open_tag" в PHP включена? ([short_open_tag на php.net](https://www.php.net/manual/ru/ini.core.php#ini.short-open-tag))

**Comment by Genzo4** [comment]
Была отключена. Включил, пошла установка дальше.
