### ISSUE TITLE
Ссылки на скачивание последних версий aspia на главной странице

### ISSUE THREAD

**Issue by Genzo4** [lumian/aspia-webui#6]
Здравствуйте.
Пожелание: сделать возможность загрузки последних версий программ с сайта обновлялки (aspia-webui).

Подробнее:
у нас есть компьютер без скажем хоста Aspia. Чтобы его поставить, надо взять где-то инсталятор. А где его взять? С флэшки? С сайта автора? С сетевого диска? Но ведь он физически уже есть на сайте apia-webui. Т.е. может сделать, чтобы когда заходишь на начальную страницу aspia-webui, выводилась не только форма входа в админку, но и ссылки на последние версии aspia (клиента и т.д.).

**Comment by lumian** [comment]
Интересно, подумаю над этим.

**Comment by lumian** [comment]
На главной странице (Раздел "Обновления") есть кнопка для скачивания инсталлятора.
В разделе "Инсталляторы" есть кнопка для скачивания инсталлятора.

Думаю, что этого достаточно. Все ссылки доступны после логина в систему.

**Закрыто.**
