### ISSUE TITLE
PHP 8.1 Не работает

### ISSUE THREAD

**Issue by z51chv** [lumian/aspia-webui#8]
Как минимум не работает установка.

Выходит много подобных сообщений:

Severity: Warning
Message: Undefined variable $file
Filename: views/installer.php
Line Number: 65

Severity: Warning
Message: Trying to access array offset on value of type bool
Filename: views/installer.php
Line Number: 106

**Comment by lumian** [comment]
Исправлено обновлением фреймворка.
**Закрыто.**
